boostcampwm-2021/iOS02-SanTa

- SanTa/SanTa.xcodeproj/project.pbxproj
- SanTa/SanTa/Application/AppCoordinator.swift
- SanTa/SanTa/Application/SceneDelegate.swift
- SanTa/SanTa/Application/TabBarController.swift
- SanTa/SanTa/MapScene/MapViewController.swift
- SanTa/SanTa/MapScene/MapViewCoordinator.swift
- SanTa/SanTa/MountainListScene/MountainListViewController.swift
- SanTa/SanTa/MountainListScene/MountainListViewCoordinator.swift
- SanTa/SanTa/RecordingScene/RecordingViewController.swift
- SanTa/SanTa/RecordingScene/RecordingViewCoordinator.swift
- SanTa/SanTa/ResultScene/ResultViewController.swift
- SanTa/SanTa/ResultScene/ResultViewCoordinator.swift
- SanTa/SanTa/SettingsScene/SettingsViewController.swift
- SanTa/SanTa/SettingsScene/SettingsViewCoordinator.swift
Coordinator Pattern 적용, Tab Bar Controller
🔒 Close #8
- Coordinator
- TabBarController
- TabBarController
- 이름 추가
- TabBar background color  추가
- icon 추가
> [Feat] Coordinator Pattern 적용

- SanTa/SanTa.xcodeproj/project.pbxproj
- SanTa/SanTa/Application/SceneDelegate.swift
- SanTa/SanTa/RecordingScene/RecordingViewController+Extension.swift
- SanTa/SanTa/RecordingScene/RecordingViewController.swift
- SanTa/SanTa/Resources/Base.lproj/LaunchScreen.storyboard
🔒 Close #11
- RecordingViewController+Extension
- RecordingViewController Views 초기화
- RecordingViewController Views Constraints 적용
> [Feat] RecodingView Layout 구현

- SanTa/SanTa.xcodeproj/project.pbxproj
- SanTa/SanTa/MountainListScene/MountainCell.swift
- SanTa/SanTa/MountainListScene/MountainListViewController.swift
- SanTa/SanTa/MountainListScene/MountainListViewCoordinator.swift
🔒 Close #10
- MountainListViewCoordinator.swift
- MountainListViewController.swift
- MountainCell.swift (추가)
- 목록 화면 View 구성
> [Feat] 산 목록화면 View 구현

- SanTa/SanTa.xcodeproj/project.pbxproj
- SanTa/SanTa.xcodeproj/xcshareddata/xcschemes/SanTa.xcscheme
- SanTa/SanTa/MapScene/ClusterAnnotationView.swift
- SanTa/SanTa/MapScene/MapViewController.swift
- SanTa/SanTa/MapScene/MountainAnnotationView.swift
- SanTa/SanTa/Resources/Info.plist
🔒 Close #15 #16 #17 #18 #19 
- 변경된 파일명
- Info.plist 
- MountainAnnotationView.swift
- ClusterAnnotationView.swift
- 기능 목록
- Apple 지도
- 위치 서비스 권한 획득
- 현재 위치로 지도 확대 및 축소
- 클러스터링
> [Feat] MapView Layout 및 마커 구현

- SanTa/SanTa/MapScene/MapViewController.swift
🔒 Close #23 
- 변경된 파일명
- 기능 목록
- 화면을 확대하거나 위치를 옮겨도 클러스터링이 잘 적용 된다
> [Fix] 클러스터링이 적용되지 않는 버그 수정

- SanTa/SanTa.xcodeproj/project.pbxproj
- SanTa/SanTa/MountainListScene/MountainListViewController.swift
- SanTa/SanTa/SettingsScene/MapOptionCell.swift
- SanTa/SanTa/SettingsScene/PaddingLabel.swift
- SanTa/SanTa/SettingsScene/SettingsCell.swift
- SanTa/SanTa/SettingsScene/SettingsViewController.swift
- SanTa/SanTa/SettingsScene/ToggleOptionCell.swift
🔒 Close #27 
- SettingsViewController.swift
- ToggleOptionCell.swift (추가)
- MapOptionCell.swift (추가)
- PaddingLabel.swift (추가)
- 설정화면 View 기획서 형태와 유사하게 구현
- dummy data를 작성하여 뷰에 보여지도록 구현
> [Feat] 설정화면 View 구현

- SanTa/SanTa/MapScene/MapViewController.swift
🔒 Close #33 
- MainViewController.swift
> [Fix] Merge 과정에서 중복된 코드 제거

- SanTa/SanTa/MapScene/MapViewCoordinator.swift
- SanTa/SanTa/Resources/SanTa.xcdatamodeld/SanTa.xcdatamodel/contents
🔒 Close #53 
- 변경된 파일명
- Santa.xcdatamodeld
- MapViewCoordinator
> [Fix] Merge 이후 실행 불가한 Xcode에러 해결

- SanTa/SanTa/MapScene/MapViewController.swift
> [Refactor] MapViewController 리펙토링

- SanTa/SanTa/MapScene/MapViewController.swift
> [Fix] 종이 비행기 버튼이 나타나지 않는 버그 수정

- SanTa/SanTa/Application/AppCoordinator.swift
- SanTa/SanTa/Resources/SanTa.xcdatamodeld/SanTa.xcdatamodel/contents
🔒 Close #66 
- SanTa.xcdatamodeld
- RecordEntity, LocationEntity 참조 관계 지정
> [Fix] Core Data Entity Inverse 지정

- SanTa/SanTa/MapScene/MapViewCoordinator.swift
- SanTa/SanTa/RecordingScene/RecordingUseCase.swift
- SanTa/SanTa/RecordingScene/RecordingViewController.swift
- SanTa/SanTa/RecordingScene/RecordingViewCoordinator.swift
- SanTa/SanTa/RecordingScene/RecordingViewModel.swift
🔒 Close #48, #59
- RecordingViewCoordinator
- MapViewCoordinator
- CoreData에 RecordModel 저장
> [Feature] RecordingViewModel 구조 개선 및 CoreData 저장

- SanTa/SanTa/MapScene/MapViewCoordinator.swift
- SanTa/SanTa/RecordingScene/RecordingUseCase.swift
- SanTa/SanTa/RecordingScene/RecordingViewController.swift
- SanTa/SanTa/RecordingScene/RecordingViewCoordinator.swift
- SanTa/SanTa/RecordingScene/RecordingViewModel.swift
🔒 Close #68 
- MapViewCoordinator
- RecordingViewCoordinator
- RecordingViewCoordinator를 MapViewCoordinator로 하여금 인스턴스 관리를 할 수 있게 함
> [Bug] RecordingViewCoordinator 인스턴스가 사라지지 않는 문제 

- SanTa/SanTa/MapScene/MapViewController.swift
> [Fix] 클러스터링이 정상적으로 작동하지 않는 버그 수정

- SanTa/SanTa/MapScene/MapViewController.swift
> [Fix] 중복된 코드 제거

- SanTa/SanTa/MapScene/MapViewController.swift
> [Refactor] 권한 변경시 Switch문을 이용한 분기 사용

- SanTa/SanTa.xcodeproj/project.pbxproj
- SanTa/SanTa.xcodeproj/xcshareddata/xcschemes/SanTa.xcscheme
- SanTa/SanTa/Persistences/UserDefaultsStorage.swift
- SanTa/SanTa/SettingsScene/MapOptionCell.swift
- SanTa/SanTa/SettingsScene/Option.swift
- SanTa/SanTa/SettingsScene/Settings.swift
- SanTa/SanTa/SettingsScene/SettingsRepository.swift
- SanTa/SanTa/SettingsScene/SettingsUsecase.swift
- SanTa/SanTa/SettingsScene/SettingsViewController.swift
- SanTa/SanTa/SettingsScene/SettingsViewCoordinator.swift
- SanTa/SanTa/SettingsScene/SettingsViewModel.swift
- SanTa/SanTa/SettingsScene/ToggleOptionCell.swift
- SanTa/SanTa/SettingsScene/UserDefaultsSettingsStorage.swift
- SanTa/SettingsSceneTests/SettingsUsecaseTests.swift
- SanTa/SettingsSceneTests/SettingsViewModelTests.swift
🔒 Close #73, #74, #83, #84, #95
- ToggleOptionCell.swift
- MapOptionCell.swift
- SettingsViewCoordinator.swift
- SettingsViewController.swift
- SettingsViewModel.swift (추가)
- SettingsUsecase.swift (추가)
- SettingsRepository.swift (추가)
- UserDefaultsSettingsStorage.swift (추가)
- Settings.swift (추가)
- Option.swift (추가)
- Cell 디자인 변경
- 설정변화 시 UserDefaults 에 데이터 저장
- 설정화면 전체적인 구현 완성
> [Feature] 설정화면 구현

- SanTa/SanTa.xcodeproj/project.pbxproj
- SanTa/SanTa/RecordingScene/CoreDataRecordStorage.swift
- SanTa/SanTa/RecordingScene/Record.swift
- SanTa/SanTa/RecordingScene/RecordingModel.swift
- SanTa/SanTa/RecordingScene/RecordingUseCase.swift
- SanTa/SanTa/Resources/Info.plist
🔒 Close #81 
- Record
- CoreDataRecordStorage
- Recording Background Task
- Timer Date 형식 교환
> [Feature] Recording Background Task 구현

- SanTa/SanTa/Application/AppCoordinator.swift
- SanTa/SanTa/Application/SceneDelegate.swift
- SanTa/SanTa/MapScene/MapViewController.swift
- SanTa/SanTa/Persistences/UserDefaultsStorage.swift
- SanTa/SanTa/SettingsScene/SettingsRepository.swift
- SanTa/SanTa/SettingsScene/SettingsUsecase.swift
- SanTa/SanTa/SettingsScene/SettingsViewCoordinator.swift
- SanTa/SettingsSceneTests/SettingsUsecaseTests.swift
🔒 Close #100
- SanTa/SanTa/Application/AppCoordinator.swift
- SanTa/SanTa/Application/SceneDelegate.swift
- SanTa/SanTa/MapScene/MapViewController.swift
- SanTa/SanTa/Persistences/UserDefaultsStorage.swift
- SanTa/SanTa/SettingsScene/SettingsRepository.swift
- SanTa/SanTa/SettingsScene/SettingsViewCoordinator.swift
- SanTa/SanTa/SettingsScene/SettingsUsecase.swift
- SanTa/SettingsSceneTests/SettingsUsecaseTests.swift
- 앱 처음 실행 시 설정의 UserDefaults의 초기값을 세팅한다.
> [Feature] 앱 처음 실행 시 UserDefaults 값 세팅

- SanTa/SanTa.xcodeproj/project.pbxproj
- SanTa/SanTa/RecordingScene/RecordingUseCase.swift
- SanTa/SanTa/RecordingScene/RecordingViewController.swift
- SanTa/SanTa/RecordingScene/RecordingViewCoordinator.swift
- SanTa/SanTa/RecordingScene/RecordingViewModel.swift
- SanTa/SanTa/RecordingTitleScene/RecordingTitleViewController.swift
- SanTa/SanTa/RecordingTitleScene/RecordingTitleViewCoordinator.swift
🔒 Close #98, #99, #102, #103, #105, #109 
- RecordingTitleViewController
- RecordingViewCoordinator
- RecordingTitleViewCoordinator
- 제목이 TextField의 최대 크기를 넘어갈 시 동적으로 Text의 크기를 조절
- 등산 기록 제목을 입력해 저장
- 측정 제목 화면 View 작성 
- Coordinator를 이용해 측정 제목 화면으로 이동
- 등산 기록의 제목이 20자를 넘기지 않는다
- 기록 제목을 입력하지 않으면 빈 문자열로 이름이 저장
> [Feature] RecordingTitleView 완료

- SanTa/SanTa.xcodeproj/project.pbxproj
- SanTa/SanTa/RecordingScene/Record.swift
- SanTa/SanTa/RecordingScene/RecordingModel.swift
- SanTa/SanTa/RecordingScene/RecordingUseCase.swift
- SanTa/SanTa/RecordingScene/RecordingViewController.swift
- SanTa/SanTa/RecordingScene/RecordingViewCoordinator.swift
- SanTa/SanTa/RecordingScene/RecordingViewModel.swift
- SanTa/SanTa/RecordingTitleScene/RecordingTitleViewController.swift
- SanTa/SanTa/RecordingTitleScene/RecordingTitleViewCoordinator.swift
🔒 Close #111, #112, #113, #114, #115 
- Record
- RecodingViewController
- 이동거리 측정 일시정지 및 재시작 
- 고도 측정 일시정지 및 재시작 
- 걸음 수 측정 일시정지 및 재시작
- 정지 버튼을 누르면 측정 화면 일시 정지 버튼의 이미지를 변경
> [Feature] RecordingView 일시정지 기능

- SanTa/SanTa/MapScene/MapViewController.swift
> [Fix] 잘못된 self 제거

- SanTa/SanTa/MapScene/MapViewController.swift
- SanTa/SanTa/MapScene/MapViewCoordinator.swift
> [Refactor] protocol을 이용한 간접참조

- SanTa/SanTa/MapScene/MapViewController.swift
- SanTa/SanTa/MapScene/MapViewCoordinator.swift
- SanTa/SanTa/MapScene/MapViewModel.swift
- SanTa/SanTa/MapScene/MapViewRepository.swift
- SanTa/SanTa/MapScene/MapViewUseCase.swift
🔒 Close #116 
- 변경된 파일명
- MapViewRepository.swift
- MapViewUseCase.swift
- 기능 목록
- 설정 화면에서 기록한 지도 형식을 불러올 수 있다
- 불러온 지도 형식을 토대로 지도 형식을 변경할 수 있다
> [Feature] 지도 형식 변경 기능

- SanTa/SanTa/MapScene/MapViewCoordinator.swift
- SanTa/SanTa/RecordingScene/RecordingViewCoordinator.swift
- SanTa/SanTa/RecordingTitleScene/RecordingTitleViewCoordinator.swift
🔒 Close #123 
- 변경된 파일명
- RecordingViewCoordinator.swift
- RecordingTitleViewCoordinator.swfit
> [Fix] Merge 이후 발생한 컴파일 에러 해결

- SanTa/SanTa/Application/AppCoordinator.swift
- SanTa/SanTa/MapScene/MapViewCoordinator.swift
- SanTa/SanTa/Persistences/UserDefaultsStorage.swift
- SanTa/SanTa/RecordingScene/RecordingViewCoordinator.swift
- SanTa/SanTa/SettingsScene/SettingsViewCoordinator.swift
🔒 Close #125
- SanTa/SanTa/Application/AppCoordinator.swift
- SanTa/SanTa/MapScene/MapViewCoordinator.swift
- SanTa/SanTa/Persistences/UserDefaultsStorage.swift
- SanTa/SanTa/RecordingScene/RecordingViewCoordinator.swift
- SanTa/SanTa/SettingsScene/SettingsViewCoordinator.swift
- Persistence 주입 구조 수정
> [Refactor] Persistence 주입 구조 수정

- SanTa/SanTa/Application/AppCoordinator.swift
- SanTa/SanTa/MapScene/MapViewCoordinator.swift
- SanTa/SanTa/Persistences/UserDefaultsStorage.swift
- SanTa/SanTa/RecordingScene/CoreDataRecordStorage.swift
- SanTa/SanTa/RecordingScene/RecordingViewCoordinator.swift
- SanTa/SanTa/SettingsScene/MapOptionCell.swift
- SanTa/SanTa/SettingsScene/SettingsViewController.swift
- SanTa/SanTa/SettingsScene/SettingsViewCoordinator.swift
- SanTa/SanTa/SettingsScene/ToggleOptionCell.swift
🔒 Close #133 
- SanTa/SanTa/SettingsScene/MapOptionCell.swift
- SanTa/SanTa/SettingsScene/SettingsViewController.swift
- SanTa/SanTa/SettingsScene/ToggleOptionCell.swift
- 설정화면 Dynamic Type Text 적용
> [Feature] 설정화면 Dynamic Type Text 적용

- SanTa/SanTa/RecordingScene/RecordingModel.swift
- SanTa/SanTa/RecordingScene/RecordingUseCase.swift
- SanTa/SanTa/RecordingScene/RecordingViewController.swift
- SanTa/SanTa/RecordingScene/RecordingViewCoordinator.swift
- SanTa/SanTa/RecordingTitleScene/RecordingTitleViewController.swift
- SanTa/SanTa/RecordingTitleScene/RecordingTitleViewCoordinator.swift
🔒 Close #126 
- RecordingViewCoordinator
- RecordingTitleViewCoordinator
- RecordingVIewController
- RecordingTitleViewController
[RecordingViewController 해제 문제](https://github.com/boostcampwm-2021/iOS02-SanTa/wiki/RecordingViewController-%EB%A9%94%EB%AA%A8%EB%A6%AC-%ED%95%B4%EC%A0%9C-%EB%AC%B8%EC%A0%9C)
> [Fix] RecordingView Dismiss 시에 크래쉬 발생 해결

- SanTa/SanTa/Persistences/CoreDataStorage.swift
- SanTa/SanTa/RecordingScene/CoreDataRecordStorage.swift
- SanTa/SanTa/RecordingScene/Record.swift
- SanTa/SanTa/RecordingScene/RecordRepository.swift
- SanTa/SanTa/RecordingScene/RecordingModel.swift
- SanTa/SanTa/RecordingScene/RecordingUseCase.swift
- SanTa/SanTa/RecordingScene/RecordingViewController+Extension.swift
- SanTa/SanTa/RecordingScene/RecordingViewController.swift
- SanTa/SanTa/RecordingScene/RecordingViewModel.swift
- SanTa/SanTa/Resources/SanTa.xcdatamodeld/SanTa.xcdatamodel/contents
🔒 Close #132, #135, #136, #137, #138 
- RecordRepository
- CoreDataRecordStorage
- CoreDataStorage
- RecordingViewController+Extension
- 수정된 측정 기록 struct에 맞게 CoreData 리팩토링
- CoreData 저장에 실패했을 경우 이벤트 추가
> [Refactor] RecordingViewController CoreData 리팩토링 및 저장 실패 이벤트 추가 

- SanTa/SanTa/ResultScene/ResultViewController.swift
🔒 Close #153 
- 변경된 파일명 
- 기능 목록
- 기록 화면 Layout
> [Feat] #153 기록 화면 Layout

- SanTa/SanTa.xcodeproj/project.pbxproj
- SanTa/SanTa/MountainDetailScene/MountainDetailViewController.swift
- SanTa/SanTa/ResultDetailScene/ResultDetailSmallerInfoView.swift
- SanTa/SanTa/ResultDetailScene/ResultDetailViewController.swift
🔒 Close #148 , #146
ResultDetailViewController
ResultDetailSmallerInfoView
MountainDetailViewController
산 상세화면 스크롤 오류 수정
기록 상세화면 뷰 추가
> [Feat] 산 상세화면 스크롤 오류 수정 및 기록 상세화면 뷰

- SanTa/SanTa.xcodeproj/project.pbxproj
- SanTa/SanTa/Persistences/CoreDataRecordStorage.swift
- SanTa/SanTa/RecordingScene/Record.swift
- SanTa/SanTa/RecordingScene/RecordingModel.swift
- SanTa/SanTa/Resources/SanTa.xcdatamodeld/SanTa.xcdatamodel/contents
- SanTa/SanTa/ResultScene/ResultRepository.swift
- SanTa/SanTa/ResultScene/ResultUseCase.swift
🔒 Close #128, #152
- SanTa/SanTa.xcodeproj/project.pbxproj
- SanTa/SanTa/Persistences/CoreDataRecordStorage.swift
- SanTa/SanTa/Resources/SanTa.xcdatamodeld/SanTa.xcdatamodel/contents
- SanTa/SanTa/ResultScene/ResultUseCase.swift
- SanTa/SanTa/RecordingScene/Record.swift
- SanTa/SanTa/RecordingScene/RecordingModel.swift
- SanTa/SanTa/ResultScene/ResultRepository.swift
- Repository가 CoreData에서 데이터를 가져온다
- 가져온 데이터를 통해 화면에 보여줄 데이터를 제공하는 기능을 가진 모델객체를 만든다.
- UseCase는 가져온 데이터를 통해 모델 인스턴스를 만들어 전달한다.
> [Feature] CoreData에서 데이터 Fetch, Model 생성

- SanTa/SanTa.xcodeproj/project.pbxproj
- SanTa/SanTa/ResultDetailScene/ResultDetailLargerInfoView.swift
- SanTa/SanTa/ResultDetailScene/ResultDetailSmallerInfoView.swift
- SanTa/SanTa/ResultDetailScene/ResultDetailViewController 2.swift
- SanTa/SanTa/ResultDetailScene/ResultDetailViewController.swift
🔒 Closes #149 
MountainListViewCoordinator.swift
MountainListViewController.swift
MountainCell.swift
정보화면 확대 / 축소
> [Feat] 기록 상세화면 정보창 확대/축소

- SanTa/SanTa/RecordingScene/Record.swift
🔒 Close #163 
- 변경된 파일명
- Record.swift
> [Refactor] #163 Record 리펙토링

- SanTa/SanTa/Application/AppCoordinator.swift
- SanTa/SanTa/RecordingScene/Record.swift
- SanTa/SanTa/ResultScene/ResultViewCoordinator.swift
🔒 Close #166 
- 변경된 파일명
- AppCoordinator.swift
- ResultViewCoordinator.swift
> [Refactor] Coordinator 의존성 주입

- SanTa/SanTa.xcodeproj/project.pbxproj
- SanTa/SanTa/Application/AppCoordinator.swift
- SanTa/SanTa/RecordingScene/Record.swift
- SanTa/SanTa/ResultScene/RecordsViewCell.swift
- SanTa/SanTa/ResultScene/ResultUseCase.swift
- SanTa/SanTa/ResultScene/ResultViewController.swift
- SanTa/SanTa/ResultScene/ResultViewCoordinator.swift
- SanTa/SanTa/ResultScene/ResultViewModel.swift
- SanTa/SanTa/ResultScene/SectionHeaderView.swift
- SanTa/SanTa/ResultScene/TotalRecordsViewCell.swift
🔒 Close #168
🔒 Close #169
🔒 Close #170
- 변경된 파일명
- RecordsViewCell.swift
- ResultUseCase.swift
- ResultViewModel.swift
- SectionHeaderView.swift
- TotalRecordsViewCell.swift
- 기능 목록
- CoreData로 부터 등산 기록을 불러올 수 있다
- Dark Mode를 지원한다
> [Feature] ResultScene Data흐름, 다크모드 구현

- SanTa/SanTa.xcodeproj/project.pbxproj
- SanTa/SanTa/RecordingPhotoScene/RecordingPhotoCoordinator.swift
- SanTa/SanTa/RecordingPhotoScene/RecordingPhotoViewController.swift
- SanTa/SanTa/RecordingScene/Record.swift
- SanTa/SanTa/RecordingScene/RecordingPhotoModel.swift
- SanTa/SanTa/RecordingScene/RecordingUseCase.swift
- SanTa/SanTa/RecordingScene/RecordingViewController.swift
- SanTa/SanTa/RecordingScene/RecordingViewCoordinator.swift
- SanTa/SanTa/Resources/Info.plist
🔒 Close #161, #160, #159, #158
- Record
- RecordingPhotoModel
- RecordingPhotoViewController
- RecordingPhotoCoordinator
- 측정 화면 중 촬영 사진 가져오기
- 측정 화면 앨범 접근 권한 얻기
> [Featrue] 측정 화면 중 촬영 된 사진 가져오기

- SanTa/SanTa/RecordingScene/Record.swift
🔒 Close #182
- 변경된 파일명
- Record.swift
> [Refactor] 고도차 계산 리펙토링

- SanTa/SanTa/ResultScene/RecordsViewCell.swift
- SanTa/SanTa/ResultScene/TotalRecordsViewCell.swift
🔒 Close #184 
- 변경된 파일명
- TotalRecordsView.swift
- RecordsViewCell.swift
> [Refactor] 반복되는 부분 리펙토링

- SanTa/SanTa/MapScene/MapViewController.swift
- SanTa/SanTa/MapScene/UIImage+Gif.swift
🔒 Close #186 
- 변경된 파일명
- UIImage+Gif.swift
- 기능 목록
- 애니메이션이 하얀 색으로 나타남
- Touch Event가 터치하자마자 발생
> [Feature] 애니메이션 색상, 버튼 터치 이벤트 변경

- SanTa/SanTa/Application/AppCoordinator.swift
- SanTa/SanTa/MapScene/MapViewController.swift
🔒 Close #192
🔒 Close #193 
- 변경된 파일명
- AppCoordinator
- MapViewController
- 기능 목록
- 탭을 변경할 때 진동을 느낄 수 있다
- 측정을 시작할 때에 진동을 느낄 수 있다
> [Feature] 진동 피드백

- SanTa/SanTa/Application/AppCoordinator.swift
🔒 Close #198 
- 변경된 파일명
- AppCoordinator.swift
- 기능 목록
- TabBar에서 Signature Color를 확인할 수 있다
> [Fix] TabBar DarkMode 대응 및 Personal Color 적용

- SanTa/SanTa/ResultScene/ResultViewController.swift
> [Refactor] ResultViewController 리펙토링

- SanTa/SanTa/ResultScene/ResultViewController.swift
> [Fix] Sticky Header 적용

- SanTa/SanTa/Resources/Assets.xcassets/RecodingResultCellColor.colorset/Contents.json
- SanTa/SanTa/ResultScene/RecordsViewCell.swift
- SanTa/SanTa/ResultScene/SectionHeaderView.swift
🔒 Close #203 
- 변경된 파일명
- Assets.xcassets
- SelectionHeaderView.swift
- RecordsViewCell.swift
> [Refactor] 기록 화면에서 DarkMode

- SanTa/SanTa/Persistences/CoreDataRecordStorage.swift
- SanTa/SanTa/RecordingScene/Record.swift
- SanTa/SanTa/RecordingScene/RecordingModel.swift
- SanTa/SanTa/RecordingScene/RecordingPhotoModel.swift
- SanTa/SanTa/RecordingScene/RecordingUseCase.swift
- SanTa/SanTa/RecordingScene/RecordingViewController.swift
- SanTa/SanTa/RecordingScene/RecordingViewModel.swift
- SanTa/SanTa/Resources/SanTa.xcdatamodeld/SanTa.xcdatamodel/contents
- SanTa/SanTa/ResultScene/ResultUseCase.swift
🔒 Close #178 
🔒 Close #179 
🔒 Close #180 
🔒 Close #181 
- Record
- CoreDataRecordStorage
- GPS 동작 중 예외처리
- 중간에 GPS가 꺼져도 정상적으로 동작할 수 있도록 함.
> [Featrue] GPS 동작 중 예외처리 완료

- SanTa/SanTa/ResultScene/RecordsViewCell.swift
- SanTa/SanTa/ResultScene/ResultViewController.swift
🔒 Close #205
- 변경된 파일명
- RecordsViewCell.swift
- 기능 목록
- 기록의 이름이 나타납니다
> [Feat] 기록 이름 표시

- SanTa/SanTa/ResultScene/ResultViewModel.swift
🔒 Close #209 
- 변경된 파일명
- ResultViewModel.swift
- 기능 목록
- 오늘이라면 날짜가 표시되지 않는다
- 어제라면 날짜를 어제라고 표시한다
- 그 이전이라면 월과 일을 표시한다
> [Feature] 기록의 날짜를 구분하여 표기하는 기능

- SanTa/SanTa/Application/AppDelegate.swift
🔒 Close #211 
- 변경된 파일명
- AppDelegate.swift
> [Fix] 가로모드 통제

- SanTa/SanTa/MapScene/MapViewController.swift
- SanTa/SanTa/MapScene/MapViewCoordinator.swift
- SanTa/SanTa/MapScene/MapViewModel.swift
- SanTa/SanTa/MapScene/MapViewUseCase.swift
🔒 Close #219
- 변경된 파일명
- MapViewUseCase.swift
> [Refactor] MapScene 리펙토링

- SanTa/SanTa/MapScene/MapViewController.swift
- SanTa/SanTa/MapScene/MapViewCoordinator.swift
- SanTa/SanTa/MapScene/MapViewModel.swift
- SanTa/SanTa/MapScene/MapViewUseCase.swift
- SanTa/SanTa/MountainDetailScene/MountainDetailUseCase.swift
- SanTa/SanTa/MountainDetailScene/MountainDetailViewCoordinator.swift
🔒 Close #220 
- 변경된 파일명
- MountainDetailUseCase.swift
- MountainDetailViewCoordinator.swift
> [Refactor] MountainDetailScene 리펙토링

- SanTa/SanTa/MapScene/MapViewCoordinator.swift
- SanTa/SanTa/MountainListScene/MountainListViewCoordinator.swift
🔒 Close #234 
- 변경된 파일명
- 기능 목록
> [Hotfix] MountainDetailCoordinator Location 매개변수 수정

- SanTa/SanTa/Persistences/UserDefaultsStorage.swift
- SanTa/SanTa/SettingsScene/Settings.swift
- SanTa/SanTa/SettingsScene/SettingsUsecase.swift
- SanTa/SanTa/SettingsScene/SettingsViewController.swift
- SanTa/SanTa/SettingsScene/SettingsViewModel.swift
🔒 Close #236 
- SanTa/SanTa/Persistences/UserDefaultsStorage.swift
- SanTa/SanTa/SettingsScene/Settings.swift
- SanTa/SanTa/SettingsScene/SettingsUsecase.swift
- SanTa/SanTa/SettingsScene/SettingsViewController.swift
- SanTa/SanTa/SettingsScene/SettingsViewModel.swift
- #224 피드백 적용
- 설정화면 등산로 표시 항목 제거
> [Refactor] 설정화면 리펙토링

- SanTa/SanTa/MountainListScene/MountainCell.swift
- SanTa/SanTa/MountainListScene/MountainListViewController.swift
- SanTa/SanTa/Persistences/UserDefaultsStorage.swift
- SanTa/SanTa/SettingsScene/Settings.swift
- SanTa/SanTa/SettingsScene/SettingsUsecase.swift
- SanTa/SanTa/SettingsScene/SettingsViewController.swift
- SanTa/SanTa/SettingsScene/SettingsViewModel.swift
🔒 Close #242 
- SanTa/SanTa/MountainListScene/MountainCell.swift
- SanTa/SanTa/MountainListScene/MountainListViewController.swift
- 산 목록 화면 보이스오버 적용
> [Feature] 산 목록 화면 보이스오버 적용

- SanTa/RecordingSceneTest/RecordingUseCaseTest.swift
- SanTa/RecordingSceneTests/RecordingUseCaseTests.swift
- SanTa/SanTa.xcodeproj/project.pbxproj
- SanTa/SanTa.xcodeproj/xcshareddata/xcschemes/SanTa.xcscheme
- SanTa/SanTa/Persistences/CoreDataRecordStorage.swift
- SanTa/SanTa/RecordingScene/RecordRepository.swift
- SanTa/SanTa/RecordingScene/RecordingUseCase.swift
- SanTa/SanTa/RecordingScene/RecordingViewModel.swift
🔒 Close #237 
- RecordRepository
- CoreDataRecordStorage
- RecordingUseCase 테스트 코드 추가 및 테스트를 하기 적절한 구조로 변경
> [Refactor] RecordingUseCase TestCode

- SanTa/SanTa/MountainDetailScene/MountainDetailViewController.swift
- SanTa/SanTa/MountainDetailScene/MountainDetailViewCoordinator.swift
- SanTa/SanTa/MountainListScene/MountainListViewController.swift
- SanTa/SanTa/MountainListScene/MountainListViewCoordinator.swift
🔒 Close #144
- MountainViewController
- MountainViewCoordinator
- MountainList Cell Touch시 Push 동작
> [Feature] MountainList Cell Touch시 Push 동작

- SanTa/SanTa/Resources/Info.plist
🔒 Close #248
- 변경된 파일명
- info.plist
> [Fix] 앱이 기록화면에서 크래시가 나는 버그 해결

- SanTa/SanTa/ResultDetailScene/ResultDetailModel.swift
- SanTa/SanTa/ResultDetailScene/ResultDetailSmallerInfoView.swift
- SanTa/SanTa/ResultDetailScene/ResultDetailViewController.swift
- SanTa/SanTa/ResultDetailScene/ResultDetailViewModel.swift
🔒 Close #253 Close #252 
ResultDetailScene/ResultDetailSmallerInfoView.swift
ResultDetailScene/ResultDetailViewController.swift
ResultDetailScene/ResultDetailViewModel.swift
정보 숫자 볼드체
정보 ViewModel 사용성 개선
변경 버튼에 액션 추가 (얼럿만)
> [Feature] 개별 기록화면 정보 ViewModel 수정, 변경 버튼 액션

- SanTa/SanTa.xcodeproj/project.pbxproj
- SanTa/SanTa/MapScene/MapViewController.swift
- SanTa/SanTa/Persistences/CoreDataRecordStorage.swift
- SanTa/SanTa/RecordingScene/Record.swift
- SanTa/SanTa/RecordingScene/RecordingModel.swift
- SanTa/SanTa/RecordingScene/RecordingViewController.swift
- SanTa/SanTa/RecordingTitleScene/RecordingTitleViewController.swift
- SanTa/SanTa/RecordingTitleScene/RecordingTitleViewCoordinator.swift
- SanTa/SanTa/Resources/SanTa.xcdatamodeld/SanTa.xcdatamodel/contents
- SanTa/SanTa/ResultDetailScene/ResultDetailModel.swift
- SanTa/SanTa/ResultDetailScene/ResultDetailRepository.swift
- SanTa/SanTa/ResultDetailScene/ResultDetailUseCase.swift
- SanTa/SanTa/ResultDetailScene/ResultDetailViewController.swift
- SanTa/SanTa/ResultDetailScene/ResultDetailViewCoordinator.swift
- SanTa/SanTa/ResultDetailScene/ResultDetailViewModel.swift
- SanTa/SanTa/ResultScene/ResultUseCase.swift
🔒 Close #255 Close #256 Close #263
Persistences/CoreDataRecordStorage.swift
RecordingScene/RecordingViewController.swift
RecordingTitleScene/RecordingTitleViewController.swift
RecordingTitleScene/RecordingTitleViewCoordinator.swift
ResultDetailScene/ResultDetailModel.swift
ResultDetailScene/ResultDetailRepository.swift
ResultDetailScene/ResultDetailUseCase.swift
ResultDetailScene/ResultDetailViewController.swift
ResultDetailScene/ResultDetailViewCoordinator.swift
ResultDetailScene/ResultDetailViewModel.swift
- 기록 삭제
- 기록 제목 변경
> [Feature] 기록 삭제 및 제목 변경, 이동 경로 그리기

- SanTa/SanTa/MapScene/MapViewController.swift
- SanTa/SanTa/MountainDetailScene/MountainDetailViewController.swift
- SanTa/SanTa/RecordingScene/RecordingModel.swift
- SanTa/SanTa/RecordingScene/RecordingViewController+Extension.swift
- SanTa/SanTa/RecordingScene/RecordingViewController.swift
- SanTa/SanTa/RecordingScene/RecordingViewModel.swift
🔒 Close #258, #259, #261
- SanTa/SanTa/RecordingScene/RecordingViewController+Extension.swift
- SanTa/SanTa/RecordingScene/RecordingViewController.swift
- SanTa/SanTa/MapScene/MapViewController.swift
- SanTa/SanTa/RecordingScene/RecordingModel.swift
- SanTa/SanTa/RecordingScene/RecordingViewModel.swift
- SanTa/SanTa/MountainDetailScene/MountainDetailViewController.swift
- 산 상세화면, 시작화면, 측정화면  VoiceOver
> [Feature] 산 상세화면, 시작화면, 측정화면  VoiceOver 적용

- SanTa/SanTa.xcodeproj/project.pbxproj
- SanTa/SanTa/MountainAddingScene/MountainAddingView.swift
- SanTa/SanTa/MountainAddingScene/MountainAddingViewController.swift
- SanTa/SanTa/MountainAddingScene/MountainAddingViewCoordinator.swift
- SanTa/SanTa/MountainAddingScene/MountainAddingViewModel.swift
- SanTa/SanTa/MountainAddingScene/MountainAddingViewRepository.swift
- SanTa/SanTa/MountainAddingScene/MountainAddingViewUseCase.swift
- SanTa/SanTa/Persistences/CoreDataMountainStorage.swift
- SanTa/SanTa/Resources/SanTa.xcdatamodeld/SanTa.xcdatamodel/contents
🔒 Close #264
🔒 Close #265
🔒 Close #266
🔒 Close #267
- 변경된 파일명
- project.pbxproj
- CoreDataMountainStorage.swift
- SanTa.xcdatamodeld
- MountainAddingView.swift
- MountainAddingViewController.swift
- MountainAddingViewCoordinator.swift
- MountainAddingViewModel.swift
- MountainAddingViewRepository.swift
- MountainAddingViewUseCase.swift
- 기능 목록
- 장소 등록 화면 레이아웃을 확인할 수 있다.
- 산 이름을 설정할 수 있다.
- 산 설명을 설정할 수 있다.
- 저장소에 산을 저장할 수 있다.
> [Feat] 장소 등록 화면 레이아웃, 산 이름, 설명, 저장소에 저장하기

- SanTa/SanTa.xcodeproj/project.pbxproj
- SanTa/SanTa/Application/AppDelegate.swift
- SanTa/SanTa/Resources/SanTa.xcdatamodeld/SanTa.xcdatamodel/contents
- SanTa/SanTa/ResultDetailScene/DetailCell.swift
- SanTa/SanTa/ResultDetailScene/DetailHeader.swift
- SanTa/SanTa/ResultDetailScene/ResultDetailLargerInfoView.swift
- SanTa/SanTa/ResultDetailScene/ResultDetailSmallerInfoView.swift
- SanTa/SanTa/ResultDetailScene/ResultDetailViewController.swift
- SanTa/SanTa/ResultScene/ResultUseCase.swift
🔒 Close #128 
🔒 Close #149 
- project.pbxproj 
- SanTa.xcdatamodel/contents 
- DetailCell.swift  DetailHeader.swift 
- ResultDetailLargerInfoView.swift
- ResultDetailSmallerInfoView.swift
- ResultDetailViewController.swift 
- ResultUseCase.swift 
-  Repository를 통한 CoreData fetch
- 기록 상세화면 정보창 스와이프
> [Feature] 기록 상세화면 정보창 스와이프

- SanTa/SanTa/ResultDetailScene/ResultDetailViewController.swift
- SanTa/SanTa/ResultScene/ResultUseCase.swift
- ResultDetailViewController.swift 
- ResultUseCase.swift
> [HotFix] 머지 후 컨플릭트 해결

- SanTa/SanTa/MapScene/MapViewController.swift
- SanTa/SanTa/MountainAddingScene/MountainAddingView.swift
- SanTa/SanTa/MountainAddingScene/MountainAddingViewController.swift
- SanTa/SanTa/RecordingPhotoScene/RecordingPhotoViewController.swift
- SanTa/SanTa/RecordingScene/RecordingViewController+Extension.swift
- SanTa/SanTa/RecordingScene/RecordingViewController.swift
- SanTa/SanTa/ResultScene/RecordsViewCell.swift
- SanTa/SanTa/ResultScene/ResultViewController.swift
- SanTa/SanTa/ResultScene/ResultViewModel.swift
- SanTa/SanTa/ResultScene/SectionHeaderView.swift
- SanTa/SanTa/ResultScene/TotalRecordsViewCell.swift
🔒 Close #261, #262, #272
- SanTa/SanTa/RecordingScene/RecordingViewController.swift
- SanTa/SanTa/ResultScene/RecordsViewCell.swift
- SanTa/SanTa/ResultScene/ResultViewController.swift
- SanTa/SanTa/ResultScene/ResultViewModel.swift
- SanTa/SanTa/ResultScene/SectionHeaderView.swift
- SanTa/SanTa/ResultScene/TotalRecordsViewCell.swift
- SanTa/SanTa/RecordingPhotoScene/RecordingPhotoViewController.swift
- SanTa/SanTa/MapScene/MapViewController.swift
- SanTa/SanTa/RecordingScene/RecordingViewController+Extension.swift
- SanTa/SanTa/RecordingScene/RecordingViewController.swift
- SanTa/SanTa/MountainAddingScene/MountainAddingView.swift
- SanTa/SanTa/MountainAddingScene/MountainAddingViewController.swift
- 장소등록 화면,  사진허용 화면, 기록화면 Voiceover 적용
- #262 피드백 적용
> [Feat] 장소등록 화면,  사진허용 화면, 기록화면 Voiceover 적용

- SanTa/SanTa/RecordingScene/Record.swift
- SanTa/SanTa/ResultDetailScene/DetailCell.swift
- SanTa/SanTa/ResultDetailScene/DetailHeader.swift
- SanTa/SanTa/ResultDetailScene/ResultDetailLargerInfoView.swift
- SanTa/SanTa/ResultDetailScene/ResultDetailModel.swift
- SanTa/SanTa/ResultDetailScene/ResultDetailViewController.swift
- SanTa/SanTa/ResultDetailScene/ResultDetailViewModel.swift
🔒 Close #150, #286
RecordingScene/Record.swift
ResultDetailScene/DetailCell.swift
ResultDetailScene/ResultDetailModel.swift
ResultDetailScene/ResultDetailViewController.swift
- 기능 목록
> [Feature] 개별 기록 화면 상세 정보

- SanTa/SanTa/MapScene/MapViewCoordinator.swift
- SanTa/SanTa/MountainAddingScene/MountainAddingView.swift
- SanTa/SanTa/MountainAddingScene/MountainAddingViewController.swift
- SanTa/SanTa/MountainAddingScene/MountainAddingViewCoordinator.swift
- SanTa/SanTa/MountainAddingScene/MountainAddingViewModel.swift
🔒 Close #282
- 변경된 파일명
- MountainAddingView.swift
- MountainAddingViewController.swift
- MountainAddingViewCoordinator.swift
- MountainAddingViewModel.swift
> [Refactor] 장소 등록 화면 리펙토링

- SanTa/SanTa/MapScene/MapViewCoordinator.swift
- SanTa/SanTa/MapScene/MapViewModel.swift
- SanTa/SanTa/MapScene/MapViewRepository.swift
- SanTa/SanTa/MountainAddingScene/MountainAddingView.swift
- SanTa/SanTa/MountainAddingScene/MountainAddingViewController.swift
- SanTa/SanTa/MountainAddingScene/MountainAddingViewCoordinator.swift
- SanTa/SanTa/MountainAddingScene/MountainAddingViewModel.swift
- SanTa/SanTa/MountainAddingScene/MountainAddingViewUseCase.swift
- SanTa/SanTa/Persistences/CoreDataMountainStorage.swift
- SanTa/SanTa/Resources/SanTa.xcdatamodeld/SanTa.xcdatamodel/contents
🔒 Close #288 
- 변경된 파일명
- MapViewRepository.swift
- MountainAddingViewModel.swift
- MountainAddingViewUseCase.swift
- CoreDataMountainStorage.swift
- SanTa.xcdatamodeld
- 기능 목록
- 지도 화면에서 추가한 산을 확인할 수 있다
- 산의 주소지를 확인할 수 있다
> [Feature] 지도 화면에서 저장한 산 확인하기

- SanTa/SanTa/MapScene/MapViewCoordinator.swift
- SanTa/SanTa/MapScene/MapViewModel.swift
- SanTa/SanTa/MapScene/MapViewRepository.swift
- SanTa/SanTa/MountainAddingScene/MountainAddingView.swift
- SanTa/SanTa/MountainAddingScene/MountainAddingViewController.swift
- SanTa/SanTa/MountainAddingScene/MountainAddingViewCoordinator.swift
- SanTa/SanTa/MountainAddingScene/MountainAddingViewModel.swift
- SanTa/SanTa/MountainAddingScene/MountainAddingViewUseCase.swift
- SanTa/SanTa/Persistences/CoreDataMountainStorage.swift
- SanTa/SanTa/Resources/SanTa.xcdatamodeld/SanTa.xcdatamodel/contents
🔒 Close #290 
- 변경된 파일명
- MountainAddingView.swift
> [Fix] 장소 등록 화면 키보드 버그

- SanTa/SanTa/MapScene/MapViewController.swift
- SanTa/SanTa/MapScene/MapViewCoordinator.swift
- SanTa/SanTa/MapScene/MapViewModel.swift
- SanTa/SanTa/MapScene/MapViewRepository.swift
- SanTa/SanTa/MountainAddingScene/MountainAddingView.swift
- SanTa/SanTa/MountainAddingScene/MountainAddingViewController.swift
- SanTa/SanTa/MountainAddingScene/MountainAddingViewCoordinator.swift
- SanTa/SanTa/MountainAddingScene/MountainAddingViewModel.swift
- SanTa/SanTa/MountainAddingScene/MountainAddingViewUseCase.swift
- SanTa/SanTa/Persistences/CoreDataMountainStorage.swift
- SanTa/SanTa/Resources/SanTa.xcdatamodeld/SanTa.xcdatamodel/contents
🔒 Close #293 
- 변경된 파일명
- MapViewRepository.swift
> [Fix] 산 마커가 2개씩 겹쳐지는 버그

- SanTa/SanTa/MapScene/MapViewController.swift
- SanTa/SanTa/MapScene/MapViewCoordinator.swift
- SanTa/SanTa/MapScene/MapViewModel.swift
- SanTa/SanTa/MapScene/MapViewRepository.swift
- SanTa/SanTa/MountainAddingScene/MountainAddingView.swift
- SanTa/SanTa/MountainAddingScene/MountainAddingViewController.swift
- SanTa/SanTa/MountainAddingScene/MountainAddingViewCoordinator.swift
- SanTa/SanTa/MountainAddingScene/MountainAddingViewModel.swift
- SanTa/SanTa/MountainAddingScene/MountainAddingViewUseCase.swift
- SanTa/SanTa/Persistences/CoreDataMountainStorage.swift
- SanTa/SanTa/Resources/SanTa.xcdatamodeld/SanTa.xcdatamodel/contents
🔒 Close #295 
- 변경된 파일명
- MountainAddingViewController.swift
- MountainAddingViewModel.swift
- 기능 목록
- 장소 등록 후 즉시 적용
> [Feature] 장소 등록 후 즉시 적용 기능

- SanTa/SanTa/MountainAddingScene/MountainAddingViewUseCase.swift
🔒 Close #297 
- 변경된 파일명
- MountainAddingViewUseCase.swift
> [Fix] 등록한 산의 고도 표기 수정

- SanTa/SanTa/MapScene/MapViewController.swift
🔒 Close #299 
- 변경된 파일명
- 기능 목록
- Tracking Button의 색상이 Signature Color를 표현한다
> [Feat] Tracking Button 색상 변경

- SanTa/SanTa/MountainDetailScene/MountainDetailViewController.swift
- SanTa/SanTa/MountainDetailScene/MountainDetailViewCoordinator.swift
- SanTa/SanTa/MountainListScene/MountainListViewCoordinator.swift
🔒 Close #304
🔒 Close #305 
- 변경된 파일명
- MountainDetailViewCoordinator.swift
- MountainDetailViewController.swift
- MountainListViewCoordinator.swift
> [Fix] 산 상세 화면 버그 수정

- SanTa/SanTa.xcodeproj/project.pbxproj
- SanTa/SanTa/ResultDetailImagesScene/DetailImagesCell.swift
- SanTa/SanTa/ResultDetailImagesScene/ResultDetailImageViewCoordinator.swift
- SanTa/SanTa/ResultDetailImagesScene/ResultDetailImagesViewController.swift
- SanTa/SanTa/ResultDetailImagesScene/ResultDetailImagesViewCoordinator.swift
- SanTa/SanTa/ResultDetailScene/ResultDetailViewController.swift
- SanTa/SanTa/ResultDetailScene/ResultDetailViewCoordinator.swift
- SanTa/SanTa/ResultDetailScene/ThumbnailView.swift
- SanTa/SanTa/ResultDetailThumbnailScene/ResultDetailThumbnailViewController.swift
- SanTa/SanTa/ResultDetailThumbnailScene/ResultDetailThumbnailViewCoordinator.swift
🔒 Close #279 
- SanTa.xcodeproj/project.pbxproj 
- ResultDetailImagesScene/DetailImagesCell.swift
- ResultDetailImagesViewController.swift
- ResultDetailImagesViewCoordinator.swift 
- ResultDetailViewController.swift 
- ResultDetailViewCoordinator.swift
- ThumbnailView.swift 
- ResultDetailThumbnailViewController.swift
- ResultDetailThumbnailViewCoordinator.swift 
- 사진을 터치하면 해당 사진을 확대하여 볼 수 있음
> [Feature] 사진을 터치하면 해당 사진을 확대

- SanTa/SanTa/ResultDetailScene/DetailCell.swift
- SanTa/SanTa/ResultDetailScene/ResultDetailLargerInfoView.swift
- SanTa/SanTa/ResultDetailScene/ResultDetailModel.swift
- SanTa/SanTa/ResultDetailScene/ResultDetailViewController.swift
- SanTa/SanTa/ResultDetailScene/ResultDetailViewModel.swift
🔒 Close #301  Close #302 
ResultDetailScene/DetailCell.swift
ResultDetailScene/ResultDetailModel.swift
> [Refactor]  상세 정보 셀 configure 리팩토링, 경사도 로직 수정

- SanTa/SanTa/ResultDetailScene/ResultDetailUseCase.swift
- SanTa/SanTa/ResultDetailScene/ResultDetailViewController.swift
- SanTa/SanTa/ResultDetailScene/ResultDetailViewModel.swift
🔒 Close #277
- 변경된 파일명
- ResultDetailUseCase.swift
- ResultDetailViewController.swift
- ResultDetailViewModel.swift
- 기능 목록
- 썸네일 이미지를 보거나 보지 않도록 토글하는 기능
> [Feat] 사진 썸네일 이미지 토글 기능

- SanTa/SanTa/ResultScene/ResultViewModel.swift
🔒 Close #315 
- 변경된 파일명
- ResultViewModel.swift
> [Fix] 고도차가 제대로 표기되지 않는 버그

- SanTa/SanTa.xcodeproj/project.pbxproj
- SanTa/SanTa/ResultDetailScene/PinView.swift
- SanTa/SanTa/ResultDetailScene/ResultDetailUseCase.swift
- SanTa/SanTa/ResultDetailScene/ResultDetailViewController.swift
- SanTa/SanTa/ResultDetailScene/ResultDetailViewModel.swift
🔒 Close #325 
- 변경된 파일명
- project.pbxproj
- PinView.swift
- ResultDetailViewController.swift
- 기능 목록
- 출발점 및 종료점을 마커로 확인할 수 있다
- 마커를 누르면 출발점인지, 종료점인지 나타내어 준다
> [Feature] 기록 상세 화면 출발점 및 종료점 표시

- SanTa/SanTa/MountainListScene/MountainListViewController.swift
🔒 Close #329
- 변경된 파일명
- MountainListViewController.swift
> [Fix] 산 상세 화면에서 고도에 단위가 표시되지 않는 버그 수정

- SanTa/SanTa.xcodeproj/project.pbxproj
- SanTa/SanTa/ResultDetailScene/DetailCell.swift
- SanTa/SanTa/ResultDetailScene/DetailHeader.swift
- SanTa/SanTa/ResultDetailScene/ResultDetailLargerInfoView.swift
- SanTa/SanTa/ResultDetailScene/ResultDetailModel.swift
- SanTa/SanTa/ResultDetailScene/ResultDetailViewController.swift
- SanTa/SanTa/ResultDetailScene/ResultDetailViewCoordinator.swift
- SanTa/SanTa/ResultDetailScene/ResultDetailViewModel.swift
🔒 Close #286 Close #318 Close #313
ResultDetailScene/DetailCell.swift
ResultDetailScene/DetailHeader.swift
ResultDetailScene/ResultDetailLargerInfoView.swift
ResultDetailScene/ResultDetailModel.swift
ResultDetailScene/ResultDetailViewController.swift
ResultDetailScene/ResultDetailViewCoordinator.swift
ResultDetailScene/ResultDetailViewModel.swift
헤더뷰 날짜, 시작시간, 종료시간 표시
일부 기기에서 개별 기록화면 레이아웃이 무너지는 현상 수정
> [Feature] 헤더뷰 정보 표시

- SanTa/SanTa/RecordingTitleScene/RecordingTitleViewCoordinator.swift
🔒 Close #312 
- SanTa/SanTa/RecordingTitleScene/RecordingTitleViewController.swift
> [Refactor] RecordingTitleViewController 리펙토링

- SanTa/SanTa/RecordingScene/RecordRepository.swift
- SanTa/SanTa/RecordingScene/RecordingModel.swift
- SanTa/SanTa/RecordingScene/RecordingUseCase.swift
- SanTa/SanTa/RecordingScene/RecordingViewController.swift
- SanTa/SanTa/RecordingScene/RecordingViewModel.swift
- SanTa/SanTa/ResultDetailScene/ResultDetailModel.swift
- SanTa/SanTa/ResultDetailScene/ResultDetailViewController.swift
🔒 Close #273 
🔒 Close #314 
🔒 Close #319 
🔒 Close #322 
- RecordRepository.swift 
- RecordingModel.swift 
- RecordingUseCase.swift 
- RecordingViewController.swift 
- RecordingViewModel.swift
- ResultDetailModel.swift 
- gps 정확도 상승
- CoreMotion 권한 예외 처리
- 설정 화면, 측정 화면 사진 기록 설정 연결
> [Refactor] RecordingScene 리팩토링 및 예외 처리

- SanTa/SanTa/ResultDetailScene/ResultDetailViewController.swift
🔒 Close #331
- 변경된 파일명
- ResultDetailViewController.swift
> [Fix] 사진 모아보기 이미지

- SanTa/SanTa/ResultDetailScene/ResultDetailViewCoordinator.swift
🔒 Close #333
- 변경된 파일명
- ResultDetailViewCoordinator.swift
> [Fix] 기록화면 네비게이션 바

- SanTa/SanTa/ResultDetailScene/ResultDetailModel.swift
- SanTa/SanTa/ResultDetailScene/ResultDetailViewModel.swift
> [HOTFIX] 평균속도 이동거리 버그 수정

- SanTa/SanTa.xcodeproj/project.pbxproj
- SanTa/SanTa/RecordingScene/Record.swift
- SanTa/SanTa/ResultDetailScene/ResultDetailModel.swift
🔒 Close #336 
SanTa/SanTa.xcodeproj/project.pbxproj
SanTa/SanTa/RecordingScene/Record.swift
SanTa/SanTa/ResultDetailScene/ResultDetailModel.swift
- Locations 구조체 추가
- 경사도 로직 수정
- MountainGeoCodingTool 폴더 삭제
> [Feat] Locations 구조체 추가, 경사도 계산 로직 수정

- SanTa/SanTa.xcodeproj/project.pbxproj
- SanTa/SanTa/RecordingScene/Record.swift
- SanTa/SanTa/ResultDetailScene/ResultDetailModel.swift
🔒 Close #338 
SanTa/SanTa/RecordingScene/Record.swift
SanTa/SanTa/ResultDetailScene/ResultDetailModel.swift
> [Refactor] 고도 로직 수정

- SanTa/SanTa/MountainDetailScene/MountainDetailViewCoordinator.swift
- SanTa/SanTa/ResultScene/ResultViewController.swift
기록 화면 상단의 요역을 터치하면 크래쉬, 목록 화면 검색창이 사라지는 버그
🔒 Close #340
🔒 Close #341  
- 변경된 파일명
- MountainDetailViewCoodinator.swift
> [Fix] 기록 화면, 목록 화면 버그 해결

- SanTa/ResultSceneTests/ResultSceneTests.swift
- SanTa/SanTa.xcodeproj/project.pbxproj
- SanTa/SanTa.xcodeproj/xcshareddata/xcschemes/SanTa.xcscheme
- SanTa/SanTa/Persistences/CoreDataRecordStorage.swift
- SanTa/SanTa/ResultScene/ResultRepository.swift
- SanTa/SanTa/ResultScene/ResultUseCase.swift
- SanTa/SanTa/ResultScene/ResultViewModel.swift
🔒 Close #343, #327
- SanTa/SanTa/Persistences/CoreDataRecordStorage.swift
- SanTa/ResultSceneTests/ResultSceneTests.swift
- SanTa/SanTa.xcodeproj/project.pbxproj
- SanTa/SanTa.xcodeproj/xcshareddata/xcschemes/SanTa.xcscheme
- SanTa/SanTa/ResultScene/ResultRepository.swift
- SanTa/SanTa/ResultScene/ResultUseCase.swift
- SanTa/SanTa/ResultScene/ResultViewModel.swift
- 기록화면 리펙토링 및 유닛 테스트
> [REFACTOR] 기록화면 리펙토링 및 유닛 테스트

- SanTa/ResultSceneTests/ResultSceneTests.swift
- SanTa/SanTa.xcodeproj/project.pbxproj
- SanTa/SanTa.xcodeproj/xcshareddata/xcschemes/SanTa.xcscheme
- SanTa/SanTa/Persistences/CoreDataRecordStorage.swift
- SanTa/SanTa/ResultDetailScene/DetailCell.swift
- SanTa/SanTa/ResultDetailScene/DetailHeader.swift
- SanTa/SanTa/ResultDetailScene/ResultDetailLargerInfoView.swift
- SanTa/SanTa/ResultDetailScene/ResultDetailSmallerInfoView.swift
- SanTa/SanTa/ResultDetailScene/ResultDetailViewController.swift
- SanTa/SanTa/ResultScene/ResultRepository.swift
- SanTa/SanTa/ResultScene/ResultUseCase.swift
- SanTa/SanTa/ResultScene/ResultViewModel.swift
🔒 Close #349 
SanTa/ResultSceneTests/ResultSceneTests.swift
SanTa/SanTa/ResultDetailScene/DetailCell.swift
SanTa/SanTa/ResultDetailScene/DetailHeader.swift
SanTa/SanTa/ResultDetailScene/ResultDetailLargerInfoView.swift
SanTa/SanTa/ResultDetailScene/ResultDetailSmallerInfoView.swift
SanTa/SanTa/ResultDetailScene/ResultDetailViewController.swift
- 기록상세화면 Voiceover 적용
> [FEATURE] 기록상세화면 Voiceover 적용

- SanTa/RecordingSceneTests/RecordingUseCaseTests.swift
- SanTa/RecordingSceneTests/RecordingViewModelTests.swift
- SanTa/SanTa.xcodeproj/project.pbxproj
- SanTa/SanTa/Application/AppDelegate.swift
- SanTa/SanTa/MountainListScene/MountainCell.swift
- SanTa/SanTa/RecordingScene/RecordingViewModel.swift
- SanTa/SanTa/ResultDetailScene/ResultDetailViewController.swift
- SanTa/SanTa/ResultScene/ResultViewController.swift
- SanTa/SanTa/ResultScene/SectionHeaderView.swift
🔒 Close #352 
🔒 Close #347 
🔒 Close #346 
🔒 Close #345 
🔒 Close #238 
- RecordingUseCaseTests.swift 
- RecordingViewModelTests.swift 
- project.pbxproj 
- AppDelegate.swift
- MountainCell.swift 
- RecordingViewModel.swift
- ResultDetailViewController.swift 
- SectionHeaderView.swift
> [Refactor] ResultDetailView 사진 로직, RecordingViewModel UnitTest 추가

- SanTa/SanTa/MountainDetailScene/MountainDetailViewController.swift
- SanTa/SanTa/MountainListScene/MountainListViewController.swift
- SanTa/SanTa/Persistences/CoreDataRecordStorage.swift
- SanTa/SanTa/RecordingScene/Record.swift
- SanTa/SanTa/Resources/SanTa.xcdatamodeld/SanTa.xcdatamodel/contents
- SanTa/SanTa/ResultDetailScene/ResultDetailModel.swift
- SanTa/SanTa/ResultDetailScene/ResultDetailViewModel.swift
- SanTa/SanTa/ResultScene/ResultViewModel.swift
🔒 Close #344 Close #350 Close #354
SanTa/SanTa/MountainDetailScene/MountainDetailViewController.swift
SanTa/SanTa/MountainListScene/MountainListViewController.swift
SanTa/SanTa/RecordingScene/Record.swift
SanTa/SanTa/ResultDetailScene/ResultDetailModel.swift
SanTa/SanTa/ResultDetailScene/ResultDetailViewModel.swift
SanTa/SanTa/ResultScene/ResultViewModel.swift
> [Refactor] 빈 데이터 값에 대응하도록 자료구조 수정, 일부 계산로직 수정

- SanTa/MapSceneTests/MapSceneTests.swift
- SanTa/MountainAddingSceneTests/MountainAddingSceneTests.swift
- SanTa/SanTa.xcodeproj/project.pbxproj
- SanTa/SanTa.xcodeproj/xcshareddata/xcschemes/SanTa.xcscheme
🔒 Close #363
🔒 Close #364 
- 변경된 파일명
- MapSceneTest.swift
- MountainAddingSceneTest.swift
- project.pbxproj
- SanTa.xcscheme
> [Test] #363, #364 MapScene, MountainAddingScene 테스트 코드 작성

- SanTa/MountainListSceneTests/MountainListSceneTests.swift
- SanTa/RecordingSceneTests/RecordingUseCaseTests.swift
- SanTa/RecordingSceneTests/RecordingViewModelTests.swift
- SanTa/RecordingSceneTests/TestRecordingRepository.swift
- SanTa/SanTa.xcodeproj/project.pbxproj
- SanTa/SanTa.xcodeproj/xcshareddata/xcschemes/MountainListSceneTests.xcscheme
- SanTa/SanTa.xcodeproj/xcshareddata/xcschemes/SanTa.xcscheme
- SanTa/SanTa/Scenes/MountainListScene/MountainListViewRepository.swift
- SanTa/SanTa/Scenes/MountainListScene/MountainListViewUseCase.swift
🔒 Close #362 
- MountainListSceneTests.swift 
- RecordingUseCaseTests.swift 
- RecordingViewModelTests.swift
- TestRecordingRepository.swift
- MountainListViewRepository.swift
- MountainListViewUseCase.swift
> [Test] MountainList UnitTest

- SanTa/ResultDetailAltitudeTest/ResultDetailAltitudeTest.swift
- SanTa/SanTa.xcodeproj/project.pbxproj
- SanTa/SanTa.xcodeproj/xcshareddata/xcschemes/SanTa.xcscheme
- SanTa/SanTa/Scenes/ResultDetailScene/ResultDetailModel.swift
🔒  Close #361 
SanTa/ResultDetailTest/ResultDetailTest.swift
SanTa/SanTa/Entities/Location.swift
SanTa/SanTa/Scenes/ResultDetailScene/ResultDetailModel.swift
> [Test] 고도 테스트 

- SanTa/SanTa.xcodeproj/xcshareddata/xcschemes/SanTa.xcscheme
- SanTa/SanTa/Scenes/MountainDetailScene/MountainDetailViewController.swift
🔒 Close #303
MountainDetailViewController.swift
> [Feat] #303 산 상세 화면 스크롤 삭제

- SanTa/SanTa/Scenes/ResultDetailScene/ResultDetailModel.swift
🔒 Close #368
ResultDetailModel.swift
> [BUG] Pace 계산 로직 수정

- SanTa/SanTa/Scenes/ResultDetailScene/ResultDetailModel.swift
- SanTa/SanTa/Scenes/ResultDetailScene/ResultDetailViewModel.swift
🔒 Close #371 
- 변경된 파일명
- ResultDetailViewModel.swift
> [Fix] 기록을 터치하였을 때 앱이 크래시나는 버그

- SanTa/SanTa/Scenes/RecordingScene/RecordingModel.swift
> [Fix] #375 음성 안내 로직 수정

- MountainGenerator/Extensions.swift
- MountainGenerator/GeoCoderResponse.swift
- MountainGenerator/MountainModel.swift
- MountainGenerator/main.swift
- SanTa/SanTa/Scenes/ResultDetailScene/ResultDetailModel.swift
🔒 Close #377
ResultDetailModel.swift
> [BUG] 이동거리가 일치 하지 않는 문제 수정

- MountainGenerator/Extensions.swift
- MountainGenerator/GeoCoderResponse.swift
- MountainGenerator/MountainModel.swift
- MountainGenerator/main.swift
🔒 Close #378
MountainGenerator/Extensions.swift
MountainGenerator/GeoCoderResponse.swift
MountainGenerator/MountainModel.swift
MountainGenerator/main.swift
> [Docs] 산 데이터 추출 파일 추가

- SanTa/SanTa/Scenes/MapScene/MountainAnnotationView.swift
🔒 Close #384
- 변경된 파일명
- MountainAnnotationView.swift
> [Fix] 지도 화면에서 마커가 깜빡이는 버그 해결
